name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run dev
